#ifndef SRC_CONFIG_H_
#define SRC_CONFIG_H_

#include"Port.h"

#define CLAW_CONTINUE_SPEED 0.1
#define CLAW_SPEED 1

#ifdef DEBUG
#define CLAW_TESTING_SPEED 0.5
#endif

#define UPPER_MAXSPEED 0.8
#define UPPER_UPMAXSPEED 0.4/UPPER_MAXSPEED
#define UPPER_BRAKESPEED -0.7/UPPER_MAXSPEED
#define UPPER_CONTINUE_SPEED 0.2/UPPER_MAXSPEED
#define UPPER_HOLD_SPEED -0.15/UPPER_MAXSPEED
#define UPPER_LIMITPOSITION 40000
#define UPPER_MAXPOSITION 73000
#define UPPER_MAXGROW_POSITION 2500
#define TANKDRIVE_POSITION_MAXSPEED 0.4

//Auto
#define DRIVE_SPEED_AUTO 0.65

#define kP 0.03
#define kI 0.00
#define kD 0.00
#define kF 0.00

#endif /* SRC_CONFIG_H_ */
