#ifndef SRC_PORT_H_
#define SRC_PORT_H_

//#define ONEDRIVER
#define TWODRIVER

//CLAW PORT
#define CLAW_LEFT_SOLENOID 0
#define CLAW_RIGHT_SOLENOID 1
#define CLAW_LEFT_MOTOR 0
#define CLAW_RIGHT_MOTOR 7

//DRIVETRAIN PORT
#define DRIVETRAIN_LEFTFORWARD_MOTOR 3
#define DRIVETRAIN_LEFTMIDDLE_MOTOR 4
#define DRIVETRAIN_LEFTBACKWARD_MOTOR 5

#define DRIVETRAIN_RIGHTFORWARD_MOTOR 0
#define DRIVETRAIN_RIGHTMIDDLE_MOTOR 1
#define DRIVETRAIN_RIGHTBACKWARD_MOTOR 2

//ELEVATOR PORT
#define ELEVATOR_LEFT_MOTOR 1
#define ELEVATOR_RIGHT_MOTOR 6
#define ELEVATOR_BUTTON 2

//CLIMB PORT
#define CLIMB_SOLENOID 9

//LEFTSTICK
#define LEFTSTICK_PORT 0
#define SWITCHCLIMBMODE 9

#ifdef ONEDRIVER
#define UPBUTTON 3
#define DOWNBUTTON 2
#endif


//RIGHTSTICK PORT
#define RIGHTSTICK_PORT 1

#ifdef ONEDRIVER
#define OPENBUTTON 1
#define INBUTTON 2
#define OUTBUTTON 3
#endif


//CONTROLSTICK PORT
#define CONTROLSTICK_PORT 2

#ifdef TWODRIVER
#define OPENBUTTON 1
#define INBUTTON 6
#define OUTAXIS 3
#define UPBUTTON 5
#define DOWNAXIS 2

#endif

#endif /* SRC_PORT_H_ */
